name: Stasis Shield
cost: 3 Clarity
flavor: You freeze time just long enough to bring the victim to safety!
keywords:
  - Psionic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self, or one creature or object
trigger: The target takes damage.
metadata:
  class: talent
  cost: 3 Clarity
  cost_amount: 3
  cost_resource: Clarity
  feature_type: ability
  file_basename: Stasis Shield
  file_dpath: Talent/8th-Level Features
  item_id: stasis-shield-3-clarity
  item_index: "01"
  item_name: Stasis Shield (3 Clarity)
  level: 8
  scc:
    - mcdm.heroes.v1:feature.ability.talent.8th-level-feature:stasis-shield-3-clarity
  scdc:
    - 1.1.1:13.2.1.2:01
  source: mcdm.heroes.v1
  type: feature/ability/talent/8th-level-feature
effects:
  - effect: The target is teleported to an unoccupied space adjacent to you, taking
      no damage and suffering no additional effects if this movement would get
      them out of harm's way.
  - effect: You can't target yourself, and you take the damage and any additional
      effects instead of the target.
    name: Strained
