name: No Dying on My Watch
cost: 5 Focus
flavor: You prioritize saving an ally over your own safety.
keywords:
  - Ranged
  - Strike
  - Weapon
type: Triggered
distance: Ranged 5
target: One enemy
trigger: The target deals damage to an ally.
metadata:
  class: tactician
  cost: 5 Focus
  cost_amount: 5
  cost_resource: Focus
  feature_type: ability
  file_dpath: Tactician/2nd-Level Features
  item_id: no-dying-on-my-watch-5-focus
  item_index: "03"
  item_name: No Dying on My Watch (5 Focus)
  level: 2
  scc:
    - mcdm.heroes.v1:feature.ability.tactician.2nd-level-feature:no-dying-on-my-watch-5-focus
  scdc:
    - 1.1.1:6.2.4.5:03
  source: mcdm.heroes.v1
  type: feature/ability/tactician/2nd-level-feature
effects:
  - effect: You move up to your speed toward the triggering ally, ending this
      movement adjacent to them or in the nearest square if you can't reach an
      adjacent square. The triggering ally can spend a Recovery and gains 5
      temporary Stamina for each enemy you came adjacent to during the move. You
      then make a power roll against the target.
  - roll: Power Roll + Might
    t1: R < WEAK, the target is frightened of the triggering ally (save ends)
    t2: R < AVERAGE, the target is frightened of the triggering ally (save ends)
    t3: R < STRONG, the target is frightened of the triggering ally (save ends)
