name: Prescient Grace
cost: 5 Wrath
flavor: Gifted by a prescient vision, you warn an ally of an impending attack.
keywords:
  - Magic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self or one ally
trigger: An enemy within 10 squares starts their turn.
metadata:
  class: censor
  cost: 5 Wrath
  cost_amount: 5
  cost_resource: Wrath
  feature_type: ability
  file_dpath: Censor/2nd-Level Features
  item_id: prescient-grace-5-wrath
  item_index: "06"
  item_name: Prescient Grace (5 Wrath)
  level: 2
  scc:
    - mcdm.heroes.v1:feature.ability.censor.2nd-level-feature:prescient-grace-5-wrath
  scdc:
    - 1.1.1:9.2.7.5:06
  source: mcdm.heroes.v1
  type: feature/ability/censor/2nd-level-feature
effects:
  - effect: You can spend a Recovery to allow the target to regain Stamina equal to
      your recovery value. The target can then take their turn immediately
      before the triggering enemy.
