name: Word of Guidance
flavor: You invigorate an attacking ally with divine energy.
keywords:
  - Magic
  - Ranged
type: Triggered
distance: Ranged 10
target: One ally
trigger: The target makes an ability roll for a damage-dealing ability.
metadata:
  class: conduit
  feature_type: trait
  file_dpath: Conduit/1st-Level Features
  item_id: word-of-guidance
  item_index: "10"
  item_name: Word of Guidance
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.conduit.1st-level-feature:word-of-guidance
  scdc:
    - 1.1.1:13.1.8.1:10
  source: mcdm.heroes.v1
  type: feature/trait/conduit/1st-level-feature
effects:
  - effect: The power roll gains an edge.
  - effect: The power roll has a double edge.
    cost: Spend 1 Piety
