name: My Life for Yours
flavor: You channel some of your vitality into more resilience for you or an ally.
keywords:
  - Magic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self or one ally
trigger: The target starts their turn or takes damage.
metadata:
  class: censor
  feature_type: trait
  file_dpath: Censor/1st-Level Features
  item_id: my-life-for-yours
  item_index: "22"
  item_name: My Life for Yours
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.censor.1st-level-feature:my-life-for-yours
  scdc:
    - 1.1.1:5.1.11.1:22
  source: mcdm.heroes.v1
  type: feature/trait/censor/1st-level-feature
effects:
  - effect: You spend a Recovery and the target regains Stamina equal to your
      recovery value.
  - effect: You can end one effect on the target that is ended by a saving throw or
      that ends at the end of their turn, or a prone target can stand up.
    cost: Spend 1 Wrath
