name: Synaptic Anchor
cost: 11 Discipline
flavor: You disrupt an enemy's strike and create a feedback loop in their mind,
  preventing them from focusing on future attacks.
keywords:
  - Psionic
type: Free triggered
distance: Self; see below
target: Self or one creature
trigger: The target takes damage from another creature's ability while in the
  area of your Null Field ability.
metadata:
  class: "null"
  cost: 11 Discipline
  cost_amount: 11
  cost_resource: Discipline
  feature_type: ability
  file_dpath: Null/8th-Level Features
  item_id: synaptic-anchor-11-discipline
  item_index: "01"
  item_name: Synaptic Anchor (11 Discipline)
  level: 8
  scc:
    - mcdm.heroes.v1:feature.ability.null.8th-level-feature:synaptic-anchor-11-discipline
  scdc:
    - 1.1.1:5.1.4.2:01
  source: mcdm.heroes.v1
  type: feature/ability/null/8th-level-feature
effects:
  - effect: The target takes half the damage, and if the triggering crea ture has I
      < AVERAGE, they are dazed (save ends). While the triggering creature is
      dazed this way, they take psychic damage equal to your Intuition score
      whenever they use a main action.
