name: Furious Change
flavor: In your anger, you revert to a more bestial form.
keywords:
  - "-"
type: Triggered
distance: Ranged 10
target: One enemy
trigger: You lose Stamina and are not dying.
metadata:
  class: fury
  feature_type: trait
  file_dpath: Fury/1st-Level Features
  item_id: furious-change
  item_index: "18"
  item_name: Furious Change
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.fury.1st-level-feature:furious-change
  scdc:
    - 1.1.1:7.1.5.1:18
  source: mcdm.heroes.v1
  type: feature/trait/fury/1st-level-feature
effects:
  - effect: You gain temporary Stamina equal to your Might score and can enter your
      animal form or hybrid form.
  - effect: If you are not dying, you can spend a Recovery.
    cost: Spend 1 Ferocity
