name: Lines of Force
keywords:
  - Magic
  - Melee
type: Triggered
distance: Melee 1
target: Self or one creature
trigger: The target would be force moved.
metadata:
  class: fury
  feature_type: ability
  file_basename: Lines of Force
  file_dpath: Fury/1st-Level Features
  item_id: lines-of-force
  item_index: "11"
  item_name: Lines of Force
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.fury.1st-level-feature:lines-of-force
  scdc:
    - 1.1.1:13.2.5.1:11
  source: mcdm.heroes.v1
  type: feature/ability/fury/1st-level-feature
effects:
  - effect: You can select a new target of the same size or smaller within distance
      to be force moved instead. You become the source of the forced movement,
      determine the new target's destination, and can push the target instead of
      using the original forced movement type. Additionally, the forced movement
      distance gains a bonus equal to your Might score.
  - effect: The forced movement distance gains a bonus equal to twice your Might
      score instead.
    cost: Spend 1 Ferocity
