type: feature
feature_type: ability
name: Unearthly Reflexes
flavor: You are as elusive as a hummingbird.
keywords:
  - "-"
usage: Triggered
distance: Self
target: Self
trigger: You take damage.
metadata:
  action_type: Triggered
  class: fury
  distance: Self
  feature_type: ability
  file_basename: Unearthly Reflexes
  file_dpath: Abilities/Fury/1st-Level Features
  flavor: You are as elusive as a hummingbird.
  item_id: unearthly-reflexes
  item_index: "05"
  item_name: Unearthly Reflexes
  keywords:
    - "-"
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.fury.1st-level-feature:unearthly-reflexes
  scdc:
    - 1.1.1:11.2.5.1:05
  source: mcdm.heroes.v1
  subclass: Reaver
  target: Self
  type: feature/ability/fury/1st-level-feature
effects:
  - name: Effect
    effect: You take half the damage from the triggering effect and can shift up to
      a number of squares equal to your Agility score.
  - cost: Spend 1 Ferocity
    effect: If the damage has any potency effects associated with it, the potency is
      reduced by 1 for you.
