name: Again
flavor: You step back a split second to see if things play out a little differently.
keywords:
  - Psionic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self or one creature
trigger: The target makes an ability roll.
metadata:
  action_type: Triggered
  class: talent
  distance: Ranged 10
  feature_type: ability
  file_basename: Again
  file_dpath: Talent/1st-Level Features
  flavor: You step back a split second to see if things play out a little differently.
  item_id: again
  item_index: "13"
  item_name: Again
  keywords:
    - Psionic
    - Ranged
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.talent.1st-level-feature:again
  scdc:
    - 1.1.1:13.2.1.1:13
  source: mcdm.heroes.v1
  target: Self or one creature
  type: feature/ability/talent/1st-level-feature
effects:
  - effect: You can use this ability after seeing the result of the triggering roll.
      The target must reroll the power roll and use the new roll.
    name: Effect
