name: Again
flavor: You step back a split second to see if things play out a little differently.
keywords:
  - Psionic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self or one creature
trigger: The target makes an ability roll.
metadata:
  class: talent
  feature_type: trait
  file_dpath: Talent/1st-Level Features
  item_id: again
  item_index: "16"
  item_name: Again
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.talent.1st-level-feature:again
  scdc:
    - 1.1.1:10.1.1.1:16
  source: mcdm.heroes.v1
  type: feature/trait/talent/1st-level-feature
effects:
  - effect: You can use this ability after seeing the result of the triggering roll.
      The target must reroll the power roll and use the new roll.
