name: Feedback Loop
flavor: Creating a brief psychic link between an enemy and their target gives
  that foe a taste of their own medicine.
keywords:
  - Psionic
  - Ranged
type: Triggered
distance: Ranged 10
target: One creature
trigger: The target deals damage to an ally.
metadata:
  class: talent
  feature_type: trait
  file_dpath: Talent/1st-Level Features
  item_id: feedback-loop
  item_index: "21"
  item_name: Feedback Loop
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.talent.1st-level-feature:feedback-loop
  scdc:
    - 1.1.1:14.1.1.1:21
  source: mcdm.heroes.v1
  type: feature/trait/talent/1st-level-feature
effects:
  - effect: The target takes psychic damage equal to half the triggering damage.
