name: Repel
flavor: They aren't going anywhere, but you might!
keywords:
  - Psionic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self or one ally
trigger: The target takes damage or is force moved.
metadata:
  class: talent
  feature_type: trait
  file_dpath: Talent/1st-Level Features
  item_id: repel
  item_index: "19"
  item_name: Repel
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.talent.1st-level-feature:repel
  scdc:
    - 1.1.1:13.1.1.1:19
  source: mcdm.heroes.v1
  type: feature/trait/talent/1st-level-feature
effects:
  - effect: The target takes half the triggering damage, or the distance of the
      triggering forced movement is reduced by a number of squares equal to your
      Reason score. If the target took damage and was force moved, you choose
      the effect. If the forced movement is reduced to 0 squares, the target can
      push the source of the forced movement a number of squares equal to your
      Reason score.
