name: Coordinated Execution
cost: 9 Focus
flavor: You direct your ally to make a killing blow.
keywords:
  - Ranged
type: Free triggered
distance: Ranged 10
target: One ally
trigger: The target uses an ability to deal rolled damage to a creature while hidden.
metadata:
  class: tactician
  cost: 9 Focus
  cost_amount: 9
  cost_resource: Focus
  feature_type: ability
  file_dpath: Tactician/6th-Level Features
  item_id: coordinated-execution-9-focus
  item_index: "03"
  item_name: Coordinated Execution (9 Focus)
  level: 6
  scc:
    - mcdm.heroes.v1:feature.ability.tactician.6th-level-feature:coordinated-execution-9-focus
  scdc:
    - 1.1.1:13.2.4.3:03
  source: mcdm.heroes.v1
  type: feature/ability/tactician/6th-level-feature
effects:
  - effect: If the target of the triggering ability is not a leader or solo
      creature, they are reduced to 0 Stamina. If the target of the triggering
      ability is a minion, the entire squad is killed. If the target of the
      triggering ability is a leader or solo creature, the triggering ability's
      power roll automatically obtains a tier 3 outcome.
