name: ""
icon: Blessing and a Curse (11 Wrath)
flavor: The gods bless and damn in equal measure.
keywords:
  - Magic
  - Ranged
type: Triggered
distance: Ranged 10
target: One creature
trigger: The target makes a power roll.
metadata:
  action_type: Triggered
  class: censor
  cost: 11 Wrath
  cost_amount: 11
  cost_resource: Wrath
  distance: Ranged 10
  feature_type: ability
  file_basename: Blessing and a Curse
  file_dpath: Censor/9th-Level Features
  flavor: The gods bless and damn in equal measure.
  item_id: blessing-and-a-curse-11-wrath
  item_index: "03"
  item_name: Blessing and a Curse (11 Wrath)
  keywords:
    - Magic
    - Ranged
  level: 9
  scc:
    - mcdm.heroes.v1:feature.ability.censor.9th-level-feature:blessing-and-a-curse-11-wrath
  scdc:
    - 1.1.1:13.2.7.7:03
  source: mcdm.heroes.v1
  target: One creature
  type: feature/ability/censor/9th-level-feature
effects:
  - effect: The target obtains a tier 1 or tier 3 outcome on their power roll (your
      choice). You can then choose another target within distance, who obtains
      the opposite outcome on their next power roll.
    name: Effect
