name: Fulfill Your Destiny
cost: 11 Wrath
flavor: You have looked at various futures, and only this one works.
keywords:
  - Magic
  - Ranged
type: Triggered
distance: Ranged 10
target: One ally
trigger: You or another hero ends their turn.
metadata:
  class: censor
  cost: 11 Wrath
  cost_amount: 11
  cost_resource: Wrath
  feature_type: ability
  file_dpath: Censor/9th-Level Features
  item_id: fulfill-your-destiny-11-wrath
  item_index: "02"
  item_name: Fulfill Your Destiny (11 Wrath)
  level: 9
  scc:
    - mcdm.heroes.v1:feature.ability.censor.9th-level-feature:fulfill-your-destiny-11-wrath
  scdc:
    - 1.1.1:5.2.6.7:02
  source: mcdm.heroes.v1
  type: feature/ability/censor/9th-level-feature
effects:
  - effect: The target takes their turn after the triggering hero, and immediately
      removes all conditions and negative effects on themself. During their
      turn, the target has a double edge on poºwer rolls.
