name: Arrestor Cycle
cost: 11 Discipline
flavor: You trap your foe in a looping cycle of time, where they relive the last
  few seconds over and over again.
keywords:
  - Psionic
  - Ranged
type: Free triggered
distance: Ranged 10
target: One creature
trigger: The triggering creature starts their turn.
metadata:
  class: "null"
  cost: 11 Discipline
  cost_amount: 11
  cost_resource: Discipline
  feature_type: ability
  file_dpath: Null/9th-Level Features
  item_id: arrestor-cycle-11-discipline
  item_index: "03"
  item_name: Arrestor Cycle (11 Discipline)
  level: 9
  scc:
    - mcdm.heroes.v1:feature.ability.null.9th-level-feature:arrestor-cycle-11-discipline
  scdc:
    - 1.1.1:5.2.5.6:03
  source: mcdm.heroes.v1
  type: feature/ability/null/9th-level-feature
effects:
  - roll: Power Roll + Intuition
    t1: I < WEAK, the target loses their turn
    t2: I < AVERAGE, the target loses their turn
    t3: I < STRONG, the target loses their turn
  - effect: If the target loses their turn, the round continues as if they had
      acted. A target who doesn't lose their turn takes psychic damage equal to
      twice your Intuition score for each main action they take until the end of
      their next turn.
