name: ""
icon: Inertial Absorption (11 Discipline)
flavor: You absorb an attack to empower your body.
keywords:
  - Psionic
type: Free triggered
distance: Self
target: Self
trigger: Another creature damages you using an ability.
metadata:
  action_type: Free triggered
  class: "null"
  cost: 11 Discipline
  cost_amount: 11
  cost_resource: Discipline
  distance: Self
  feature_type: ability
  file_basename: Inertial Absorption
  file_dpath: Null/9th-Level Features
  flavor: You absorb an attack to empower your body.
  item_id: inertial-absorption-11-discipline
  item_index: "02"
  item_name: Inertial Absorption (11 Discipline)
  keywords:
    - Psionic
  level: 9
  scc:
    - mcdm.heroes.v1:feature.ability.null.9th-level-feature:inertial-absorption-11-discipline
  scdc:
    - 1.1.1:13.2.6.7:02
  source: mcdm.heroes.v1
  target: Self
  type: feature/ability/null/9th-level-feature
effects:
  - effect: You take half the damage, negate any effects associated with the damage
      for you, and gain 3 surges.
    name: Effect
