name: Time Loop
cost: 11 Discipline
flavor: You show shadows what true speed is.
keywords:
  - Psionic
type: Free triggered
distance: Self
target: Self
trigger: Another creature on the encounter map ends their turn.
metadata:
  class: "null"
  cost: 11 Discipline
  cost_amount: 11
  cost_resource: Discipline
  feature_type: ability
  file_dpath: Null/9th-Level Features
  item_id: time-loop-11-discipline
  item_index: "04"
  item_name: Time Loop (11 Discipline)
  level: 9
  scc:
    - mcdm.heroes.v1:feature.ability.null.9th-level-feature:time-loop-11-discipline
  scdc:
    - 1.1.1:5.1.4.6:04
  source: mcdm.heroes.v1
  type: feature/ability/null/9th-level-feature
effects:
  - effect: You take a bonus turn immediately after the triggering creature. This
      ability can be used only once per combat round.
