type: feature
feature_type: trait
name: Trained Assassin
metadata:
  action_type: feature
  class: shadow
  feature_type: trait
  file_basename: Trained Assassin
  file_dpath: Shadow/2nd-Level Features
  item_id: trained-assassin
  item_index: "06"
  item_name: Trained Assassin
  level: 2
  scc:
    - mcdm.heroes.v1:feature.trait.shadow.2nd-level-feature:trained-assassin
  scdc:
    - 1.1.1:11.1.2.6:06
  source: mcdm.heroes.v1
  subclass: Caustic Alchemy
  type: feature/trait/shadow/2nd-level-feature
effects:
  - effect: You know just where to cut your enemies. Whenever you make a strike that
      has no bane or double bane, and that incorporates 1 or more surges, you
      gain 1 additional surge that you can use only on that strike.
