name: Inertial Shield
flavor: You intuit the course of an incoming attack, reducing its effects.
keywords:
  - Psionic
type: Triggered
distance: Self
target: Self
trigger: You take damage.
metadata:
  class: "null"
  feature_type: trait
  file_dpath: Null/1st-Level Features
  item_id: inertial-shield
  item_index: "02"
  item_name: Inertial Shield
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.null.1st-level-feature:inertial-shield
  scdc:
    - 1.1.1:5.2.4.1:02
  source: mcdm.heroes.v1
  type: feature/trait/null/1st-level-feature
effects:
  - effect: You take half the damage.
  - effect: The potency of one effect associated with the damage is reduced by 1 for
      you.
    cost: Spend 1 Discipline
