name: Inertial Shield
flavor: You intuit the course of an incoming attack, reducing its effects.
keywords:
  - Psionic
type: Triggered
distance: Self
target: Self
trigger: You take damage.
metadata:
  action_type: Triggered
  class: "null"
  distance: Self
  feature_type: ability
  file_basename: Inertial Shield
  file_dpath: Null/1st-Level Features
  flavor: You intuit the course of an incoming attack, reducing its effects.
  item_id: inertial-shield
  item_index: "01"
  item_name: Inertial Shield
  keywords:
    - Psionic
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.null.1st-level-feature:inertial-shield
  scdc:
    - 1.1.1:13.2.6.1:01
  source: mcdm.heroes.v1
  target: Self
  type: feature/ability/null/1st-level-feature
effects:
  - effect: You take half the damage.
    name: Effect
  - effect: The potency of one effect associated with the damage is reduced by 1 for
      you.
    cost: Spend 1 Discipline
