name: Anticipating Strike
cost: 9 Discipline
flavor: You suddenly strike an enemy, then grab them in a psionically enhanced grip.
keywords:
  - Melee
  - Psionic
  - Strike
  - Weapon
type: Free trigger
distance: Melee 1
target: One creature
trigger: The target moves or uses a main action.
metadata:
  class: "null"
  cost: 9 Discipline
  cost_amount: 9
  cost_resource: Discipline
  feature_type: ability
  file_dpath: Null/4th-Level Features
  item_id: anticipating-strike-9-discipline
  item_index: "01"
  item_name: Anticipating Strike (9 Discipline)
  level: 4
  scc:
    - mcdm.heroes.v1:feature.ability.null.4th-level-feature:anticipating-strike-9-discipline
  scdc:
    - 1.1.1:5.2.6.8:01
  source: mcdm.heroes.v1
  type: feature/ability/null/4th-level-feature
effects:
  - roll: Power Roll + Agility
    t1: 7 + A damage; I < WEAK, restrained (save ends)
    t2: 10 + A damage; I < AVERAGE, restrained (save ends)
    t3: 13 + A damage; I < STRONG, restrained (save ends)
  - effect: This strike resolves before the triggering movement or main action.
