name: So Gullible
cost: 5 Insight
flavor: When your enemy strikes, you reveal you were in a different place all along.
keywords:
  - Magic
type: Free triggered
distance: Self
target: Self
trigger: Another creature targets you with a strike.
metadata:
  class: shadow
  cost: 5 Insight
  cost_amount: 5
  cost_resource: Insight
  feature_type: ability
  file_dpath: Shadow/2nd-Level Features
  item_id: so-gullible-5-insight
  item_index: "03"
  item_name: So Gullible (5 Insight)
  level: 2
  scc:
    - mcdm.heroes.v1:feature.ability.shadow.2nd-level-feature:so-gullible-5-insight
  scdc:
    - 1.1.1:5.1.2.4:03
  source: mcdm.heroes.v1
  type: feature/ability/shadow/2nd-level-feature
effects:
  - effect: You use your Clever Trick ability with no insight cost against the
      triggering creature and strike. You can teleport to an unoccupied space
      within 3 squares of that creature and can make a free strike against them.
      You can then spend a Recovery.
