name: Too Slow
cost: 5 Insight
flavor: Your foe made a big mistake.
keywords:
  - "-"
type: Free triggered
distance: Self; see below
target: Self
trigger: You use your In All This Confusion ability.
metadata:
  action_type: Free triggered
  class: shadow
  cost: 5 Insight
  cost_amount: 5
  cost_resource: Insight
  distance: Self; see below
  feature_type: ability
  file_basename: Too Slow
  file_dpath: Shadow/2nd-Level Features
  flavor: Your foe made a big mistake.
  item_id: too-slow-5-insight
  item_index: "03"
  item_name: Too Slow (5 Insight)
  keywords:
    - "-"
  level: 2
  scc:
    - mcdm.heroes.v1:feature.ability.shadow.2nd-level-feature:too-slow-5-insight
  scdc:
    - 1.1.1:13.2.2.5:03
  source: mcdm.heroes.v1
  target: Self
  type: feature/ability/shadow/2nd-level-feature
effects:
  - effect: You ignore any effects associated with the damage that triggered your In
      All This Confusion ability. Before you teleport, you can make a free
      strike against a creature who damaged you to trigger In All This
      Confusion. After you teleport, you can spend a Recovery.
