metadata:
  class: shadow
  feature_type: trait
  file_dpath: Shadow/2nd-Level Features
  item_id: trained-assassin
  item_index: "04"
  item_name: Trained Assassin
  level: 2
  scc:
    - mcdm.heroes.v1:feature.trait.shadow.2nd-level-feature:trained-assassin
  scdc:
    - 1.1.1:5.1.3.6:04
  source: mcdm.heroes.v1
  type: feature/trait/shadow/2nd-level-feature
effects:
  - effect: You know just where to cut your enemies. Whenever you make a strike that
      has no bane or double bane, and that incorporates 1 or more surges, you
      gain 1 additional surge that you can use only on that strike.
