name: Clever Trick
cost: 1 Insight
flavor: You sow a moment of confusion in combat, to your enemy's peril.
keywords:
  - Magic
type: Triggered
distance: Self
target: \\ Self
trigger: An enemy targets you with a strike.
metadata:
  class: shadow
  cost: 1 Insight
  cost_amount: 1
  cost_resource: Insight
  feature_type: ability
  file_dpath: Shadow/1st-Level Features
  item_id: clever-trick-1-insight
  item_index: "05"
  item_name: Clever Trick (1 Insight)
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.shadow.1st-level-feature:clever-trick-1-insight
  scdc:
    - 1.1.1:10.2.2.1:05
  source: mcdm.heroes.v1
  type: feature/ability/shadow/1st-level-feature
effects:
  - effect: Choose an enemy within distance of the triggering strike, including the
      enemy who targeted you. The strike targets that enemy instead.
