name: ""
icon: Hesitation Is Weakness (1 Insight)
flavor: Keep up the attack. Never give them a moment's grace.
keywords:
  - "-"
type: Free triggered
distance: Self
target: Self
trigger: Another hero ends their turn. That hero can't have used this ability to
  start their turn.
metadata:
  action_type: Free triggered
  class: shadow
  cost: 1 Insight
  cost_amount: 1
  cost_resource: Insight
  distance: Self
  feature_type: ability
  file_basename: Hesitation Is Weakness
  file_dpath: Shadow/1st-Level Features
  flavor: Keep up the attack. Never give them a moment's grace.
  item_id: hesitation-is-weakness-1-insight
  item_index: "15"
  item_name: Hesitation Is Weakness (1 Insight)
  keywords:
    - "-"
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.shadow.1st-level-feature:hesitation-is-weakness-1-insight
  scdc:
    - 1.1.1:13.2.2.1:15
  source: mcdm.heroes.v1
  target: Self
  type: feature/ability/shadow/1st-level-feature
effects:
  - effect: You take your turn after the triggering hero.
    name: Effect
