name: In All This Confusion
flavor: You vanish in a plume of black smoke to avoid danger.
keywords:
  - Magic
type: Triggered
distance: Self
target: Self
trigger: You take damage.
metadata:
  class: shadow
  feature_type: ability
  file_basename: In All This Confusion
  file_dpath: Shadow/1st-Level Features
  item_id: in-all-this-confusion
  item_index: "04"
  item_name: In All This Confusion
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.shadow.1st-level-feature:in-all-this-confusion
  scdc:
    - 1.1.1:13.2.2.1:04
  source: mcdm.heroes.v1
  type: feature/ability/shadow/1st-level-feature
effects:
  - effect: You take half the damage, then can teleport up to 4 squares after the
      triggering effect resolves.
  - effect: You teleport 1 additional square for each insight spent.
    cost: Spend 1+ Insight
