name: Night Watch
flavor: A steely dagger from out of the blue knocks another weapon off course.
keywords:
  - Ranged
  - Weapon
type: Triggered
distance: Ranged 5
target: One ally
trigger: The target takes damage from another creature's ability while you are hidden.
metadata:
  class: shadow
  feature_type: ability
  file_basename: Night Watch
  file_dpath: Shadow/4th-Level Features
  item_id: night-watch
  item_index: "01"
  item_name: Night Watch
  level: 4
  scc:
    - mcdm.heroes.v1:feature.ability.shadow.4th-level-feature:night-watch
  scdc:
    - 1.1.1:13.2.2.8:01
  source: mcdm.heroes.v1
  type: feature/ability/shadow/4th-level-feature
effects:
  - effect: The target takes half the damage. You remain hidden.
