name: Advanced Tactics
flavor: Your leadership aids an ally.
keywords:
  - Ranged
type: Triggered
distance: Ranged 10
target: One ally
trigger: The target deals damage to another creature.
metadata:
  class: tactician
  distance: Ranged 10
  feature_type: ability
  file_basename: Advanced Tactics
  file_dpath: Tactician/1st-Level Features
  flavor: Your leadership aids an ally.
  item_id: advanced-tactics
  item_index: "05"
  item_name: Advanced Tactics
  keywords:
    - Ranged
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.tactician.1st-level-feature:advanced-tactics
  scdc:
    - 1.1.1:13.2.4.1:05
  source: mcdm.heroes.v1
  target: One ally
  type: Triggered
effects:
  - effect: The target gains 2 surges, which they can use on the triggering damage.
  - effect: If the damage has any potency effect associated with it, the potency is
      increased by 1.
    cost: Spend 1 Focus
