name: Advanced Tactics
flavor: Your leadership aids an ally.
keywords:
  - Ranged
type: Triggered
distance: Ranged 10
target: One ally
trigger: The target deals damage to another creature.
metadata:
  class: tactician
  feature_type: trait
  file_dpath: Tactician/1st-Level Features
  item_id: advanced-tactics
  item_index: "04"
  item_name: Advanced Tactics
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.tactician.1st-level-feature:advanced-tactics
  scdc:
    - 1.1.1:7.1.4.1:04
  source: mcdm.heroes.v1
  type: feature/trait/tactician/1st-level-feature
effects:
  - effect: The target gains 2 surges, which they can use on the triggering damage.
  - effect: If the damage has any potency effect associated with it, the potency is
      increased by 1.
    cost: Spend 1 Focus
