name: Overwatch
flavor: Under your direction, an ally waits for just the right moment to strike.
keywords:
  - Ranged
type: Triggered
distance: Ranged 10
target: One creature
trigger: The target moves.
metadata:
  class: tactician
  feature_type: trait
  file_dpath: Tactician/1st-Level Features
  item_id: overwatch
  item_index: "12"
  item_name: Overwatch
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.tactician.1st-level-feature:overwatch
  scdc:
    - 1.1.1:10.1.4.1:12
  source: mcdm.heroes.v1
  type: feature/trait/tactician/1st-level-feature
effects:
  - effect: At any time during the target's movement, one ally can make a free
      strike against them.
  - effect: If the target has R < AVERAGE, they are slowed (EoT).
    cost: Spend 1 Focus
