name: Overwatch
flavor: Under your direction, an ally waits for just the right moment to strike.
keywords:
  - Ranged
type: Triggered
distance: Ranged 10
target: One creature
trigger: The target moves.
metadata:
  action_type: Triggered
  class: tactician
  distance: Ranged 10
  feature_type: ability
  file_basename: Overwatch
  file_dpath: Tactician/1st-Level Features
  flavor: Under your direction, an ally waits for just the right moment to strike.
  item_id: overwatch
  item_index: "13"
  item_name: Overwatch
  keywords:
    - Ranged
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.tactician.1st-level-feature:overwatch
  scdc:
    - 1.1.1:13.2.4.1:13
  source: mcdm.heroes.v1
  target: One creature
  type: feature/ability/tactician/1st-level-feature
effects:
  - effect: At any time during the target's movement, one ally can make a free
      strike against them.
    name: Effect
  - effect: If the target has R < AVERAGE, they are slowed (EoT).
    cost: Spend 1 Focus
