name: Parry
flavor: Your quick reflexes cost an enemy the precision they seek.
keywords:
  - Melee
  - Weapon
type: Triggered
distance: Melee 2
target: Self or one ally
trigger: A creature deals damage to the target.
metadata:
  class: tactician
  feature_type: trait
  file_dpath: Tactician/1st-Level Features
  item_id: parry
  item_index: "01"
  item_name: Parry
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.tactician.1st-level-feature:parry
  scdc:
    - 1.1.1:8.1.4.1:01
  source: mcdm.heroes.v1
  type: feature/trait/tactician/1st-level-feature
effects:
  - effect: You can shift 1 square. If the target is you, or if you end this shift
      adjacent to the target, the target takes half the damage. If the damage
      has any potency effect associated with it, the potency is decreased by 1.
  - effect: This ability's distance becomes Melee 1 + your Reason score, and you can
      shift up to a number of squares equal to your Reason score instead of 1
      square.
    cost: Spend 1 Focus
