name: Death Strike
cost: 9 Ferocity
flavor: Once you taste your foe's blood, you become more efficient and turn
  every killing blow into an opportunity.
keywords:
  - Melee
  - Strike
  - Weapon
type: Free triggered
distance: Melee 1
target: Self
trigger: You reduce a creature to 0 Stamina with a strike.
metadata:
  class: fury
  cost: 9 Ferocity
  cost_amount: 9
  cost_resource: Ferocity
  feature_type: ability
  file_basename: Death Strike
  file_dpath: Fury/6th-Level Features
  item_id: death-strike-9-ferocity
  item_index: "01"
  item_name: Death Strike (9 Ferocity)
  level: 6
  scc:
    - mcdm.heroes.v1:feature.ability.fury.6th-level-feature:death-strike-9-ferocity
  scdc:
    - 1.1.1:13.2.5.3:01
  source: mcdm.heroes.v1
  type: feature/ability/fury/6th-level-feature
effects:
  - effect: You target a creature adjacent to you with the same strike, using the
      same power roll as the triggering strike.
