name: My Turn!
cost: 9 Ferocity
flavor: You quickly strike back at a foe.
keywords:
  - Melee
  - Strike
  - Weapon
type: Free triggered
distance: Melee 1
target: The triggering creature
trigger: A creature causes you to be winded or dying, or damages you while you
  are winded or dying.
metadata:
  class: fury
  cost: 9 Ferocity
  cost_amount: 9
  cost_resource: Ferocity
  distance: Melee 1
  feature_type: ability
  file_basename: My Turn
  file_dpath: Fury/5th-Level Features
  flavor: You quickly strike back at a foe.
  item_id: my-turn-9-ferocity
  item_index: "04"
  item_name: My Turn! (9 Ferocity)
  keywords:
    - Melee
    - Strike
    - Weapon
  level: 5
  scc:
    - mcdm.heroes.v1:feature.ability.fury.5th-level-feature:my-turn-9-ferocity
  scdc:
    - 1.1.1:13.2.5.4:04
  source: mcdm.heroes.v1
  target: The triggering creature
  type: Free triggered
effects:
  - roll: Power Roll + Might
    t1: 6 + M damage
    t2: 9 + M damage
    t3: 13 + M damage
  - effect: You can spend a Recovery.
