name: Harmonize
cost: 3 Drama
flavor: Give the chorus a little punch.
keywords:
  - Ranged
type: Triggered
distance: Ranged 5
target: One ally
trigger: The target uses an ability that targets only one enemy and costs 3 or
  fewer of their Heroic Resource.
metadata:
  class: troubadour
  cost: 3 Drama
  cost_amount: 3
  cost_resource: Drama
  feature_type: ability
  file_basename: Harmonize
  file_dpath: Troubadour/1st-Level Features
  item_id: harmonize-3-drama
  item_index: "22"
  item_name: Harmonize (3 Drama)
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.troubadour.1st-level-feature:harmonize-3-drama
  scdc:
    - 1.1.1:13.2.3.1:22
  source: mcdm.heroes.v1
  type: feature/ability/troubadour/1st-level-feature
effects:
  - effect: The target can choose one additional target for the triggering ability.
      Any damage dealt to the additional target is sonic damage.
  - effect: You can trigger this ability when a target uses an ability that has a
      Heroic Resource cost of 3 + each additional drama spent.
    cost: Spend 1+ Drama
