name: Riposte
flavor: "\"I'd have brought treats had I known I'd be fighting a dog.\""
keywords:
  - Melee
type: Triggered
distance: Melee 1
target: Self or one ally
trigger: The target takes damage from a melee strike.
metadata:
  class: troubadour
  feature_type: trait
  file_dpath: Troubadour/1st-Level Features
  item_id: riposte
  item_index: "12"
  item_name: Riposte
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.troubadour.1st-level-feature:riposte
  scdc:
    - 1.1.1:6.1.3.1:12
  source: mcdm.heroes.v1
  type: feature/trait/troubadour/1st-level-feature
effects:
  - effect: The target makes a free strike against the creature who made the
      triggering strike.
