type: feature
feature_type: ability
name: Riposte
flavor: "\"I'd have brought treats had I known I'd be fighting a dog.\""
keywords:
  - Melee
usage: Triggered
distance: Melee 1
target: Self or one ally
trigger: The target takes damage from a melee strike.
metadata:
  action_type: Triggered
  class: troubadour
  distance: Melee 1
  feature_type: ability
  file_basename: Riposte
  file_dpath: Abilities/Troubadour/1st-Level Features
  flavor: "\"I'd have brought treats had I known I'd be fighting a dog.\""
  item_id: riposte
  item_index: "12"
  item_name: Riposte
  keywords:
    - Melee
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.troubadour.1st-level-feature:riposte
  scdc:
    - 1.1.1:11.2.3.1:12
  source: mcdm.heroes.v1
  subclass: Duelist
  target: Self or one ally
  type: feature/ability/troubadour/1st-level-feature
effects:
  - name: Effect
    effect: The target makes a free strike against the creature who made the
      triggering strike.
