name: Turnabout Is Fair Play
flavor: All's fair in love and whatever.
keywords:
  - Ranged
type: Triggered
distance: Ranged 10
target: One creature
trigger: The target makes an ability roll that has an edge, a double edge, a
  bane, or a double bane.
metadata:
  class: troubadour
  feature_type: trait
  file_dpath: Troubadour/1st-Level Features
  item_id: turnabout-is-fair-play
  item_index: "19"
  item_name: Turnabout Is Fair Play
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.troubadour.1st-level-feature:turnabout-is-fair-play
  scdc:
    - 1.1.1:13.1.3.1:19
  source: mcdm.heroes.v1
  type: feature/trait/troubadour/1st-level-feature
effects:
  - effect: An edge on the triggering roll becomes a bane, or a double edge becomes
      an edge. A bane becomes an edge, or a double bane becomes a bane.
  - effect: An edge on the triggering roll becomes a double bane, or a double edge
      is negated. A bane becomes a double edge, or a double bane is negated.
    cost: Spend 3 Drama
