type: feature
feature_type: ability
name: Turnabout Is Fair Play
flavor: All's fair in love and whatever.
keywords:
  - Ranged
usage: Triggered
distance: Ranged 10
target: One creature
trigger: The target makes an ability roll that has an edge, a double edge, a
  bane, or a double bane.
metadata:
  action_type: Triggered
  class: troubadour
  distance: Ranged 10
  feature_type: ability
  file_basename: Turnabout Is Fair Play
  file_dpath: Abilities/Troubadour/1st-Level Features
  flavor: All's fair in love and whatever.
  item_id: turnabout-is-fair-play
  item_index: "19"
  item_name: Turnabout Is Fair Play
  keywords:
    - Ranged
  level: 1
  scc:
    - mcdm.heroes.v1:feature.ability.troubadour.1st-level-feature:turnabout-is-fair-play
  scdc:
    - 1.1.1:11.2.3.1:19
  source: mcdm.heroes.v1
  subclass: Auteur
  target: One creature
  type: feature/ability/troubadour/1st-level-feature
effects:
  - name: Effect
    effect: An edge on the triggering roll becomes a bane, or a double edge becomes
      an edge. A bane becomes an edge, or a double bane becomes a bane.
  - cost: Spend 3 Drama
    effect: An edge on the triggering roll becomes a double bane, or a double edge
      is negated. A bane becomes a double edge, or a double bane is negated.
