name: Finish Them!
cost: 11 Focus
flavor: You point out an opening to your ally so they can land a killing blow.
keywords:
  - Ranged
type: Free triggered
distance: Ranged 10
target: One creature
trigger: The target is not a leader or solo creature, and becomes winded.
metadata:
  class: tactician
  cost: 11 Focus
  cost_amount: 11
  cost_resource: Focus
  feature_type: ability
  file_dpath: Tactician/8th-Level Features
  item_id: finish-them-11-focus
  item_index: "04"
  item_name: Finish Them! (11 Focus)
  level: 8
  scc:
    - mcdm.heroes.v1:feature.ability.tactician.8th-level-feature:finish-them-11-focus
  scdc:
    - 1.1.1:10.2.4.2:04
  source: mcdm.heroes.v1
  type: feature/ability/tactician/8th-level-feature
effects:
  - effect: The target is killed. Additionally, the creature who caused the target
      to be winded can spend a Recovery.
