name: Breath of Dawn Remembered
flavor: The power you channel grants the ability to get back in the fight.
keywords:
  - Green
  - Magic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self or one ally
trigger: The target starts their turn or takes damage.
metadata:
  class: elementalist
  feature_type: trait
  file_dpath: Elementalist/1st-Level Features
  item_id: breath-of-dawn-remembered
  item_index: "35"
  item_name: Breath of Dawn Remembered
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.elementalist.1st-level-feature:breath-of-dawn-remembered
  scdc:
    - 1.1.1:5.1.9.1:35
  source: mcdm.heroes.v1
  type: feature/trait/elementalist/1st-level-feature
effects:
  - effect: The target can spend a Recovery.
  - effect: The target can spend an additional Recovery for each essence spent.
    cost: Spend 1+ Essence
