name: Explosive Assistance
flavor: You add a little magic to an ally's aggression at just the right time.
keywords:
  - Fire
  - Magic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self or one ally
trigger: The target force moves a creature or object. **Effect:** The forced
  movement distance gains a bonus equal to your Reason score.
metadata:
  class: elementalist
  feature_type: trait
  file_dpath: Elementalist/1st-Level Features
  item_id: explosive-assistance
  item_index: "07"
  item_name: Explosive Assistance
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.elementalist.1st-level-feature:explosive-assistance
  scdc:
    - 1.1.1:5.1.4.1:07
  source: mcdm.heroes.v1
  type: feature/trait/elementalist/1st-level-feature
effects:
  - effect: The forced movement distance gains a bonus equal to twice your Reason
      score instead.
    cost: Spend 1 Essence
