name: Skin Like Castle Walls
flavor: You cover yourself or an ally in protective stone.
keywords:
  - Earth
  - Magic
  - Ranged
type: Triggered
distance: Ranged 10
target: Self or one ally
trigger: The target takes damage.
metadata:
  class: elementalist
  feature_type: trait
  file_dpath: Elementalist/1st-Level Features
  item_id: skin-like-castle-walls
  item_index: "14"
  item_name: Skin Like Castle Walls
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.elementalist.1st-level-feature:skin-like-castle-walls
  scdc:
    - 1.1.1:7.1.9.1:14
  source: mcdm.heroes.v1
  type: feature/trait/elementalist/1st-level-feature
effects:
  - effect: The target takes half the damage.
  - effect: If the damage has any potency effects associated with it, the potency is
      reduced by 1 for the target.
    cost: Spend 1 Essence
