name: Subtle Relocation
flavor: You call on the void to swallow and spit out an ally.
keywords:
  - Magic
  - Ranged
  - Void
type: sTriggered
distance: Ranged 10
target: Self or one ally
trigger: The target starts their turn, moves, or is force moved. **Effect:** You
  teleport the target up to a number of squares equal to your Reason score. If
  the target moves to trigger this ability, you can teleport them at any point
  during the move.
metadata:
  class: elementalist
  feature_type: trait
  file_dpath: Elementalist/1st-Level Features
  item_id: subtle-relocation
  item_index: "01"
  item_name: Subtle Relocation
  level: 1
  scc:
    - mcdm.heroes.v1:feature.trait.elementalist.1st-level-feature:subtle-relocation
  scdc:
    - 1.1.1:5.1.5.1:01
  source: mcdm.heroes.v1
  type: feature/trait/elementalist/1st-level-feature
effects:
  - effect: You teleport the target up to a number of squares equal to twice your
      Reason score instead.
    cost: Spend 1 Essence
