name: Word of Final Redemption
cost: 11 Piety
flavor: Your death will fuel our victory.
keywords:
  - Magic
  - Ranged
type: Free triggered
distance: Ranged 10
target: One creature
trigger: The target dies.
metadata:
  action_type: Free triggered
  class: conduit
  cost: 11 Piety
  cost_amount: 11
  cost_resource: Piety
  distance: Ranged 10
  feature_type: ability
  file_basename: Word of Final Redemption
  file_dpath: Conduit/9th-Level Features
  flavor: Your death will fuel our victory.
  item_id: word-of-final-redemption-11-piety
  item_index: 8
  item_name: Word of Final Redemption (11 Piety)
  keywords:
    - Magic
    - Ranged
  level: 9
  scc:
    - mcdm.heroes.v1:feature.ability.conduit.9th-level-feature:word-of-final-redemption-11-piety
  scdc:
    - 1.1.1:13.2.8.7:08
  source: mcdm.heroes.v1
  target: One creature
  type: feature/ability/conduit/9th-level-feature
effects:
  - effect: Before the target dies, you can look at their stat block and force them
      to use one ability that is a main action or a maneuver. If the ability
      costs a Heroic Resource or Malice, the creature can use it without any
      cost. For the purpose of using this ability, your allies and enemies are
      the target's allies and enemies, and you decide who the ability targets.
    name: Effect
