name: Word of Final Redemption
cost: 11 Piety
flavor: Your death will fuel our victory.
keywords:
  - Magic
  - Ranged
type: Free triggered
distance: Ranged 10
target: One creature
trigger: The target dies.
metadata:
  class: conduit
  cost: 11 Piety
  cost_amount: 11
  cost_resource: Piety
  feature_type: ability
  file_dpath: Conduit/9th-Level Features
  item_id: word-of-final-redemption-11-piety
  item_index: "06"
  item_name: Word of Final Redemption (11 Piety)
  level: 9
  scc:
    - mcdm.heroes.v1:feature.ability.conduit.9th-level-feature:word-of-final-redemption-11-piety
  scdc:
    - 1.1.1:14.2.8.7:06
  source: mcdm.heroes.v1
  type: feature/ability/conduit/9th-level-feature
effects:
  - effect: Before the target dies, you can look at their stat block and force them
      to use one ability that is a main action or a maneuver. If the ability
      costs a Heroic Resource or Malice, the creature can use it without any
      cost. For the purpose of using this ability, your allies and enemies are
      the target's allies and enemies, and you decide who the ability targets.
