name: Intercede
cost: 9 Wrath
flavor: You take your ally's place.
keywords:
  - Magic
  - Ranged
type: Free triggered
distance: Ranged 10
target: One ally
trigger: A creature makes a strike against the target.
metadata:
  action_type: Free triggered
  class: censor
  cost: 9 Wrath
  cost_amount: 9
  cost_resource: Wrath
  distance: Ranged 10
  feature_type: ability
  file_basename: Intercede
  file_dpath: Censor/6th-Level Features
  flavor: You take your ally's place.
  item_id: intercede-9-wrath
  item_index: "02"
  item_name: Intercede (9 Wrath)
  keywords:
    - Magic
    - Ranged
  level: 6
  scc:
    - mcdm.heroes.v1:feature.ability.censor.6th-level-feature:intercede-9-wrath
  scdc:
    - 1.1.1:13.2.7.3:02
  source: mcdm.heroes.v1
  subclass: Paragon
  target: One ally
  type: feature/ability/censor/6th-level-feature
effects:
  - effect: The target is unaffected by the strike and you become the target
      instead, even if you aren't a valid target for it. You take half the
      damage from the strike, and the target gains 3 surges.
    name: Effect
