name: Pain of Your Own Making
cost: 9 Wrath
flavor: You reverse the effects from an evildoer.
keywords:
  - Magic
  - Ranged
type: Free Triggered
distance: Ranged 10
target: Self or one ally
trigger: The target gains a condition or effect that is ended by a saving throw
  or that ends at the end of their turn.
metadata:
  class: censor
  cost: 9 Wrath
  cost_amount: 9
  cost_resource: Wrath
  feature_type: ability
  file_dpath: Censor/6th-Level Features
  item_id: pain-of-your-own-making-9-wrath
  item_index: "01"
  item_name: Pain of Your Own Making (9 Wrath)
  level: 6
  scc:
    - mcdm.heroes.v1:feature.ability.censor.6th-level-feature:pain-of-your-own-making-9-wrath
  scdc:
    - 1.1.1:5.2.7.3:01
  source: mcdm.heroes.v1
  type: feature/ability/censor/6th-level-feature
effects:
  - effect: The effect ends on the target and is applied to the creature who imposed
      the effect on them. That creature also takes damage equal to three times
      your Presence score.
